# Generated by Django 3.1.14 on 2022-05-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemon_previous_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='image',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='title_ru',
        ),
    ]
